<?php 
/* 
*This file is part of EC-CUBE 
* 
* Copyright (c) EC-CUBE CO.,LTD. All Rights Reserved. 
* http://www.ec-cube.co.jp/ 
* For the full copyright and license information, please view the LICENSE 
* file that was distributed with this source code. 
*/ 

// カスタムリポジトリーを作ってみた 参考動画 https://www.youtube.com/watch?v=5Zw0XCjBwyE&list=PLR6YRC-z7jlbBeF2wahIAl-e9LxVLWQty&index=19

namespace Customize\Repository;

//use 必要なオブジェクトまたはクラスを呼び出すためのもの

 use Eccube\Entity\Product; 
 use Symfony\Bridge\Doctrine\RegistryInterface; 
 use Eccube\Repository\AbstractRepository; 
 
 /**
 * CustomizeProductRepository 
 * 
 * This class was generated by the Doctrine ORM. Add your own custom 
 * repository methods below.
 */


// AbstractRepository リポジトリーに必要な機能を初期化しているので、それを継承
class CustomizeProductRepository extends AbstractRepository {
    /**
     *  CustomizeProductRepository constructor. 
     * 
     * @param RegistryInterface $registry
     */

    public function __construct(
         RegistryInterface $registry 
    ) { 
        //vscode上でエラーになっているが動いている
    parent::__construct($registry, Product::class);
    }
    /**
     * 全検索
     * 
     * @return Products|array
     */
    public function customFindAll(){
        $qb=$this->createQueryBuilder("p");
        $Products=$qb->getQuery()->getResult();
        return $Products;
    }
    /**
     * 全検索(DESC)
     * 
     * @return Products|array
     */
    public function customFindAllDesc(){
        $qb=$this->createQueryBuilder("p")
        ->orderBy("p.id","DESC");
        $Products=$qb->getQuery()->getResult();
        return $Products;
    }
    public function customFindName($name){
        $qb=$this->createQueryBuilder("p")
        ->where("p.name= :name")
        ->setParameter("name",$name)
        ->orderBy("p.id","DESC");
        $Product=$qb
        ->getQuery()
        ->getSingleResult();
        return $Product;
    }


}