<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\Rankingmanual4\Repository;

use Eccube\Entity\Master\ProductStatus;
use Eccube\Repository\AbstractRepository;
use Plugin\Rankingmanual4\Entity\RankingmanualProduct;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * RankingmanualProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RankingmanualProductRepository extends AbstractRepository
{
    /**
     * CouponRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, RankingmanualProduct::class);
    }

    /**
     * Find list.
     *
     * @return mixed
     */
    public function getRankingmanualList()
    {
        $qb = $this->createQueryBuilder('rp')
            ->innerJoin('rp.Product', 'p');
        $qb->where('rp.visible = true');
        $qb->addOrderBy('rp.sort_no', 'DESC');

        return $qb->getQuery()->getResult();
    }

    /**
     * Get max rank.
     *
     * @return mixed
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getMaxRank()
    {
        $qb = $this->createQueryBuilder('rp')
            ->select('MAX(rp.sort_no) AS max_rank');

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Get rankingmanual product by display status of product.
     *
     * @return array
     */
    public function getRankingmanualProduct()
    {
        $query = $this->createQueryBuilder('rp')
            ->innerJoin('Eccube\Entity\Product', 'p', 'WITH', 'p.id = rp.Product')
            ->where('p.Status = :Disp')
            ->andWhere('rp.visible = true')
            ->orderBy('rp.sort_no', 'DESC')
            ->setParameter('Disp', ProductStatus::DISPLAY_SHOW)
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Number of rankingmanual.
     *
     * @return mixed
     *
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countRankingmanual()
    {
        $qb = $this->createQueryBuilder('rp');
        $qb->select('COUNT(rp)');

        return $qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Move rank.
     *
     * @param array $arrRank
     *
     * @return array
     *
     * @throws \Exception
     */
    public function moveRankingmanualRank(array $arrRank)
    {
        $this->getEntityManager()->beginTransaction();
        $arrRankMoved = [];
        try {
            foreach ($arrRank as $rankingmanualId => $rank) {
                /* @var $Rankingmanual RankingmanualProduct */
                $Rankingmanual = $this->find($rankingmanualId);
                if ($Rankingmanual->getSortno() == $rank) {
                    continue;
                }
                $arrRankMoved[$rankingmanualId] = $rank;
                $Rankingmanual->setSortno($rank);
                $this->getEntityManager()->persist($Rankingmanual);
            }
            $this->getEntityManager()->flush();
            $this->getEntityManager()->commit();
        } catch (\Exception $e) {
            $this->getEntityManager()->rollback();
            throw $e;
        }

        return $arrRankMoved;
    }

    /**
     * Save rankingmanual.
     *
     * @param RankingmanualProduct $RankingmanualProduct
     *
     * @return bool
     *
     * @throws \Exception
     */
    public function saveRankingmanual(RankingmanualProduct $RankingmanualProduct)
    {
        $this->getEntityManager()->beginTransaction();
        try {
            $this->getEntityManager()->persist($RankingmanualProduct);
            $this->getEntityManager()->flush($RankingmanualProduct);
            $this->getEntityManager()->commit();
        } catch (\Exception $e) {
            $this->getEntityManager()->rollback();
            throw $e;
        }

        return true;
    }

    /**
     * Get all id of rankingmanual product.
     *
     * @return array
     */
    public function getRankingmanualProductIdAll()
    {
        $query = $this->createQueryBuilder('rp')
            ->select('IDENTITY(rp.Product) as id')
            ->where('rp.visible = true')
            ->getQuery();
        $arrReturn = $query->getScalarResult();

        return array_map('current', $arrReturn);
    }

    /**
     * 手動ランキング商品情報を削除する
     *
     * @param RankingmanualProduct $RankingmanualProduct
     *
     * @return bool
     *
     * @throws \Exception
     */
    public function deleteRankingmanual(RankingmanualProduct $RankingmanualProduct)
    {
        // 手動ランキング商品情報を書き換える
        $RankingmanualProduct->setVisible(false);

        // 手動ランキング商品情報を登録する
        return $this->saveRankingmanual($RankingmanualProduct);
    }
}
